In [1]:
!pip install tpot

Requirement already satisfied: tpot in c:\users\pert\anaconda3\lib\site-packages (0.11.6.post1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (0.16.0)
Requirement already satisfied: update-checker>=0.16 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (0.18.0)
Requirement already satisfied: scipy>=1.3.1 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (1.5.0)
Requirement already satisfied: tqdm>=4.36.1 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (4.47.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (1.0.5)
Requirement already satisfied: numpy>=1.16.3 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (1.18.5)
Requirement already satisfied: stopit>=1.1.1 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (1.1.2)
Requirement already satisfied: deap>=1.2 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (1.3.1)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\pert\anaconda3\lib\site-packages (from tpot) (0.23.1)
Requirement already satisfied: requests>=2.3.0 in c:\users\pert\anaconda3\lib\site-packages (from update-checker>=0.16->tpot) (2.24.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\pert\anaconda3\lib\site-packages (from pandas>=0.24.2->tpot) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\pert\anaconda3\lib\site-packages (from pandas>=0.24.2->tpot) (2.8.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pert\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->tpot) (2.1.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\pert\anaconda3\lib\site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pert\anaconda3\lib\site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\pert\anaconda3\lib\site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\pert\anaconda3\lib\site-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\users\pert\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24.2->tpot) (1.15.0)

In [2]:
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import RepeatedStratifiedKFold
from tpot import TPOTClassifier

# load dataset

dataframe = read_csv('HR-Employee-Attrition.csv')
dataframe.head()

C:\Users\PERT\anaconda3\lib\site-packages\tpot\builtins\__init__.py:36: UserWarning: Warning: optional dependency `torch` is not available. - skipping import of NN models.
  warnings.warn("Warning: optional dependency `torch` is not available. - skipping import of NN models.")

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
encode = LabelEncoder()
dataframe['BusinessTravel'] = encode.fit_transform(dataframe['BusinessTravel'])
dataframe['Department'] = encode.fit_transform(dataframe['Department'])
dataframe['EducationField'] = encode.fit_transform(dataframe['EducationField'])
dataframe['Attrition'] = encode.fit_transform(dataframe['Attrition'])
dataframe['Gender'] = encode.fit_transform(dataframe['Gender'])
dataframe['MaritalStatus'] = encode.fit_transform(dataframe['MaritalStatus'])
dataframe['OverTime'] = encode.fit_transform(dataframe['OverTime'])

In [7]:
# split into input and output elements
data = dataframe.values
# X = dataframe.drop('Customer_tag', axis=1)
X = dataframe[['Age','BusinessTravel','DailyRate','Department','DistanceFromHome','Education','EducationField','EnvironmentSatisfaction','Gender','JobInvolvement','JobLevel','JobSatisfaction','MaritalStatus','NumCompaniesWorked','OverTime','PercentSalaryHike','PerformanceRating','RelationshipSatisfaction','StockOptionLevel','TotalWorkingYears','TotalWorkingYears','TrainingTimesLastYear','WorkLifeBalance','YearsAtCompany','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager']]
y = dataframe['Attrition']

In [9]:
# minimally prepare dataset
#X = X.astype('float32')
#y = LabelEncoder().fit_transform(y.astype('str'))

# define model evaluation
cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1)

# define search
model = TPOTClassifier(generations=3, population_size=10, cv=cv, scoring='accuracy', verbosity=2, random_state=1, n_jobs=-1)

# perform the search
model.fit(X, y)

# export the best model
model.export('HR_best_model.py')

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.

Version 0.11.6.post1 of tpot is outdated. Version 0.11.6.post3 was released Monday December 14, 2020.

HBox(children=(FloatProgress(value=0.0, description='Optimization Progress', max=40.0, style=ProgressStyle(desâ€¦

Generation 1 - Current best internal CV score: 0.8668934240362812

Generation 2 - Current best internal CV score: 0.8668934240362812

Generation 3 - Current best internal CV score: 0.8668934240362812

Best pipeline: LogisticRegression(MaxAbsScaler(input_matrix), C=10.0, dual=False, penalty=l2)